# Generated by Django 4.2.2 on 2023-06-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_like_photo_like_to_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_publication']},
        ),
    ]
