# Generated by Django 4.2.2 on 2023-07-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment_user_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_and_time_of_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
